CREATE TABLE production_transformed(
id SERIAL PRIMARY KEY ,
quarter INTEGER,
department INTEGER,
day INTEGER,
year INTEGER,
month INTEGER,
day_of_month INTEGER,
week_of_year INTEGER,
team FLOAT,
targeted_productivity FLOAT,
smv FLOAT,
over_time FLOAT,
incentive FLOAT,
idle_time FLOAT,
idle_men FLOAT,
no_of_style_change FLOAT,
no_of_workers FLOAT,
actual_productivity FLOAT,
productivity_diff FLOAT,
over_time_per_worker FLOAT,
incentive_per_worker FLOAT,
idle_impact FLOAT,
idle_ratio FLOAT
);